### ISSUE TITLE
Could not install uWebSockets using install-mac.sh

### ISSUE THREAD

**Issue by olala7846** [udacity/CarND-Kidnapped-Vehicle-Project#11]
Hi, I was at the head of visualizer branch (10acff636041f66a5ecb10ab49dec3d41f65be87) and tried to install uWebSockets using `install-mac.sh` script on my mac. The script starts failing from line 5 complaining no `../cmakepatch.txt` to patch and there is no such file in the repository. Am I missing anything here?

thanks in advanced

Full log:
```
./install-mac.sh 
Warning: openssl is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version
Warning: libuv-1.11.0 already installed
Warning: cmake-3.8.1 already installed
Cloning into 'uWebSockets'...
remote: Counting objects: 4342, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 4342 (delta 5), reused 0 (delta 0), pack-reused 4323
Receiving objects: 100% (4342/4342), 2.36 MiB | 445.00 KiB/s, done.
Resolving deltas: 100% (2801/2801), done.
Note: checking out 'e94b6e1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at e94b6e1... Node.js: add getResponsePrototype, getRequestPrototype again
./install-mac.sh: line 5: ../cmakepatch.txt: No such file or directory
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindOpenSSL.cmake:387 (find_package_handle_standard_args)
  CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/hsin-cheng/Udacity/CarND/SDC_P8/uWebSockets/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
```

**Comment by uwesterr** [comment]
i have the same issue

**Comment by awbrown90** [comment]
I added the file cmakepatch.txt which should resolve the issue with using install-mac.sh.

**Comment by olala7846** [comment]
Thanks @awbrown90

**Comment by kevguy** [comment]
Still not working.

**Comment by Anner-deJong** [comment]
I got same errors as above on mac. cmakepatch.txt included in directory but didn't resolve.

Not explicitly mentioned in @kevguy's message, but I assumed that fixed it for him.
At least it did so for me, but I had to update it to my local version:

`cmake -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2o_2 -DOPENSSL_LIBRARIES=/usr/loca│Anners-MBP:src anner$ vim FusionEKF.cpp
l/Cellar/openssl/1.0.2o_2/lib ..`

So make sure to replace (twice!) `1.0.2o_2` with whatever version you find on your local machine.

**Comment by sethlsx** [comment]
same problem. The cmakepatch.txt doesn't work at all. Shouldn't close this issue so quickly.

**Comment by apf99** [comment]
This fixed the issue for me on MacOS...

Double-check the correct path to your openssl installation by typing:  which openssl

Once you have that then type:
cmake -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2k -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl/1.0.2k/lib

EXCEPT use your path to openssl instead.
